version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container_docker
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=TestandoDockerDB
    volumes:
      - "./db/MySql:/var/lib/mysql"



